name: main

on:
  push:
    branches: [main]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: generate-changelog-action
        uses: ScottBrenner/generate-changelog-action@v1.1.1
